# oversampling - scaling - modeling
### *임의의 테스트셋 분할

In [1]:
import pandas as pd
import numpy as np

In [2]:
test = pd.read_csv('test_encode_ver2.csv', index_col=0)
train = pd.read_csv('train_encode_ver2.csv', index_col=0)

In [3]:
train

,fraud_YN,x2,x4,x5,x7,x8,x9,x10,x14,x15,...,x16_0,x16_1,x16_2,x16_3,x16_4,x16_5,x20_0,x20_1,x20_2,x20_3
0,0,1,0,2,100,2,0,0,1.302547e+05,0,...,0,1,0,0,0,0,1,0,0,0
1,0,1,0,4,0,2,0,0,1.341009e+06,0,...,0,0,0,1,0,0,1,0,0,0
2,0,0,0,1,100,1,0,0,5.240306e+05,1209410,...,0,1,0,0,0,0,1,0,0,0
3,1,1,0,4,100,3,0,0,0.000000e+00,1217280,...,1,0,0,0,0,0,0,1,0,0
4,0,0,0,4,0,1,0,0,0.000000e+00,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12874,0,0,1,4,100,1,0,0,6.672931e+05,0,...,1,0,0,0,0,0,1,0,0,0
12875,0,0,0,2,100,2,0,0,0.000000e+00,0,...,0,1,0,0,0,0,1,0,0,0
12876,0,0,1,4,100,1,1,0,6.184394e+05,0,...,0,0,1,0,0,0,1,0,0,0
12877,0,0,0,2,100,2,0,0,0.000000e+00,0,...,0,0,0,0,1,0,1,0,0,0
12878,0,0,0,1,100,1,0,0,3.915602e+05,1188750,...,0,0,1,0,0,0,1,0,0,0

In [4]:
test

,fraud_YN,x2,x4,x5,x7,x8,x9,x10,x14,x15,...,x16_0,x16_1,x16_2,x16_3,x16_4,x16_5,x20_0,x20_1,x20_2,x20_3
0,0,0,0,4,0,3,1,0,0.000000e+00,0,...,0,1,0,0,0,0,0,1,0,0
1,0,0,1,4,100,3,1,0,2.581306e+05,12925040,...,0,0,0,1,0,0,0,1,0,0
2,0,1,0,1,100,1,0,1,0.000000e+00,4777030,...,0,1,0,0,0,0,0,1,0,0
3,0,1,0,4,100,3,1,0,2.680625e+05,250000,...,0,0,1,0,0,0,0,1,0,0
4,0,0,0,4,100,1,0,1,5.973138e+05,0,...,0,0,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3116,0,0,0,4,100,3,0,0,0.000000e+00,1708720,...,1,0,0,0,0,0,0,1,0,0
3117,0,0,0,4,100,3,0,0,0.000000e+00,0,...,0,0,0,0,1,0,1,0,0,0
3118,0,0,0,1,100,1,0,0,3.498486e+05,810230,...,1,0,0,0,0,0,0,1,0,0
3119,0,0,0,2,100,3,0,0,1.086347e+06,0,...,0,0,0,0,1,0,1,0,0,0
3120,0,1,0,4,100,1,0,0,0.000000e+00,0,...,1,0,0,0,0,0,1,0,0,0

In [5]:
socar_encode = pd.concat([train, test])
socar_encode

,fraud_YN,x2,x4,x5,x7,x8,x9,x10,x14,x15,...,x16_0,x16_1,x16_2,x16_3,x16_4,x16_5,x20_0,x20_1,x20_2,x20_3
0,0,1,0,2,100,2,0,0,1.302547e+05,0,...,0,1,0,0,0,0,1,0,0,0
1,0,1,0,4,0,2,0,0,1.341009e+06,0,...,0,0,0,1,0,0,1,0,0,0
2,0,0,0,1,100,1,0,0,5.240306e+05,1209410,...,0,1,0,0,0,0,1,0,0,0
3,1,1,0,4,100,3,0,0,0.000000e+00,1217280,...,1,0,0,0,0,0,0,1,0,0
4,0,0,0,4,0,1,0,0,0.000000e+00,0,...,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3116,0,0,0,4,100,3,0,0,0.000000e+00,1708720,...,1,0,0,0,0,0,0,1,0,0
3117,0,0,0,4,100,3,0,0,0.000000e+00,0,...,0,0,0,0,1,0,1,0,0,0
3118,0,0,0,1,100,1,0,0,3.498486e+05,810230,...,1,0,0,0,0,0,0,1,0,0
3119,0,0,0,2,100,3,0,0,1.086347e+06,0,...,0,0,0,0,1,0,1,0,0,0
3120,0,1,0,4,100,1,0,0,0.000000e+00,0,...,1,0,0,0,0,0,1,0,0,0

In [6]:
X = socar_encode.iloc[:, 1:]
y = socar_encode.iloc[:, 0]

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=44, stratify=y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((12800, 50), (3200, 50), (12800,), (3200,))

### oversampling

In [8]:
from collections import Counter

In [9]:
# Naive random over-sampling
from imblearn.over_sampling import RandomOverSampler

random = RandomOverSampler(random_state=4)
X_resampled, y_resampled = random.fit_resample(X_train, y_train)
print(sorted(Counter(y_resampled).items()))

[(0, 12767), (1, 12767)]

In [10]:
# # SMOTENC
# from imblearn.over_sampling import SMOTENC

# categorical_features = [0, 1, 2, 3, 4, 5, 6,
#                         9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
#                         27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
#                         45, 46, 47, 48, 49]

# somtenc = SMOTENC(categorical_features=categorical_features,
#                                    random_state=4)
# X_resampled, y_resampled = somtenc.fit_resample(X_train, y_train)
# print(sorted(Counter(y_resampled).items()))

In [11]:
# # ADASYN
# from imblearn.over_sampling import ADASYN

# adasyn = ADASYN()
# X_resampled, y_resampled = adasyn.fit_resample(X_train, y_train)
# print(sorted(Counter(y_resampled).items()))

In [12]:
# from imblearn.over_sampling import BorderlineSMOTE

# border = BorderlineSMOTE()
# X_resampled, y_resampled = border.fit_resample(X_train, y_train)
# print(sorted(Counter(y_resampled).items()))

In [13]:
X_resampled = round(pd.DataFrame(X_resampled, columns=X_train.columns)).astype(int)
y_resampled = pd.DataFrame(y_resampled, columns=['fraud_YN'])

# Scaling
- MinMaxScaler
    - 모든 feature가 0과 1사이에 위치하게 만듭니다.
      데이터가 2차원 셋일 경우, 모든 데이터는 x축의 0과 1 사이에, y축의 0과 1사이에 위치하게 됩니다.
- StandardScaler
    - 각 feature의 평균을 0, 분산을 1로 변경합니다. 
- RobustScaler
    - 모든 특성들이 같은 스케일을 갖게 됩니다.모든 특성들이 같은 크기를 갖는다는 점에서 StandardScaler와 비슷하지만, 평균과 분산 대신 median과 quartile을 사용합니다. RobustScaler는 이상치에 영향을 받지 않습니다.
- Normalizer
    - StandardScaler, RobustScaler, MinMaxScaler가 각 columns의 통계치를 이용한다면 Normalizer는 row마다 각각 정규화됩니다. Normalizer는 유클리드 거리가 1이 되도록 데이터를 조정합니다. (유클리드 거리는 두 점 사이의 거리를 계산할 때 쓰는 방법, L2 Distance)

In [14]:
from sklearn.preprocessing import (MinMaxScaler, StandardScaler, RobustScaler, Normalizer)

MMS = MinMaxScaler()
SS = StandardScaler()
RS = RobustScaler()
NM = Normalizer()

In [15]:
mms_train = X_resampled.copy()
ss_train = X_resampled.copy()
rs_train = X_resampled.copy()
nm_train = X_resampled.copy()

mms_test = X_test.copy()
ss_test = X_test.copy()
rs_test = X_test.copy()
nm_test = X_test.copy()

In [16]:
mms_train[['x14','x15']] = MMS.fit_transform(mms_train[['x14','x15']])
ss_train[['x14','x15']] = SS.fit_transform(ss_train[['x14','x15']])
rs_train[['x14','x15']] = RS.fit_transform(rs_train[['x14','x15']])
nm_train[['x14','x15']] = NM.fit_transform(nm_train[['x14','x15']])

mms_test[['x14','x15']] = MMS.transform(mms_test[['x14','x15']])
ss_test[['x14','x15']] = SS.transform(ss_test[['x14','x15']])
rs_test[['x14','x15']] = RS.transform(rs_test[['x14','x15']])
nm_test[['x14','x15']] = NM.transform(nm_test[['x14','x15']])

#### 적용된 스케일러별 데이터프레임 csv 저장

In [17]:
# # MinMaxScaler
# mms_train.to_csv('mms_train.csv')
# mms_test.to_csv('mms_test.csv')
# # StandardScaler
# ss_train.to_csv('ss_train.csv')
# ss_test.to_csv('ss_test.csv')
# # RobustScaler
# rs_train.to_csv('rs_train.csv')
# rs_test.to_csv('rs_test.csv')
# # Normalizer
# nm_train.to_csv('nm_train.csv')
# nm_test.to_csv('nm_test.csv')

### modeling

In [18]:
# logistic regression
import time
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced


log_clf = LogisticRegression(C=0.01, class_weight="balanced", solver="liblinear", random_state=4)
# log_clf = LogisticRegression(C=0.01, solver="lbfgs", random_state=4)
# log_clf = LogisticRegression(C=0.001, dual=False, fit_intercept=True,
#                              n_jobs=None, random_state=4, solver='liblinear')
log_clf.fit(mms_train, y_resampled)
log_pred = log_clf.predict(X_test)

# 모델과 성능 출력 함수
def get_result(model, mms_train, y_resampled, mms_test, y_test):
    start_time = time.time()
    model.fit(mms_train, y_resampled)
    pred = model.predict(mms_test)
    
    print("√", model, "\n")
    print(confusion_matrix(y_test, pred), "\n------------------------------------------------------")
    print(classification_report_imbalanced(y_test, pred, digits=6), "\n-----------------------------------------------------------------------------------")
    print('Fit time : ', time.time() - start_time, "\n-----------------------------------------------------------------------------------\n")

get_result(log_clf, mms_train, y_resampled, mms_test, y_test)
get_result(log_clf, ss_train, y_resampled, ss_test, y_test)
get_result(log_clf, rs_train, y_resampled, rs_test, y_test)
get_result(log_clf, nm_train, y_resampled, nm_test, y_test)

/Users/rudan/miniforge3/envs/tf/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/rudan/miniforge3/envs/tf/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/rudan/miniforge3/envs/tf/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)

√ LogisticRegression(C=0.01, class_weight='balanced', random_state=4,
                   solver='liblinear')

[[2358  834]
 [   4    4]]
------------------------------------------------------
                   pre       rec       spe        f1       geo       iba       sup

          0   0.998307  0.738722  0.500000  0.849118  0.607751  0.378178      3192
          1   0.004773  0.500000  0.738722  0.009456  0.607751  0.360543         8

avg / total   0.995823  0.738125  0.500597  0.847019  0.607751  0.378134      3200

-----------------------------------------------------------------------------------
Fit time :  0.06941008567810059
-----------------------------------------------------------------------------------

√ LogisticRegression(C=0.01, class_weight='balanced', random_state=4,
                   solver='liblinear')

[[2375  817]
 [   4    4]]
------------------------------------------------------
                   pre       rec       spe        f1       geo       iba       sup

          0   0.998319  0.744048  0.500000  0.852630  0.609938  0.381103      3192
          1   0.004872  0.500000  0.744048  0.009650  0.609938  0.362945         8

avg / total   0.995835  0.743437  0.500610  0.850522  0.609938  0.381058      3200

-----------------------------------------------------------------------------------
Fit time :  0.0771780014038086
-----------------------------------------------------------------------------------

√ LogisticRegression(C=0.01, class_weight='balanced', random_state=4,
                   solver='liblinear')

[[2375  817]
 [   4    4]]
------------------------------------------------------
                   pre       rec       spe        f1       geo       iba       sup

          0   0.998319  0.744048  0.500000  0.852630  0.609938  0.381103      3192
          1   0.004872  0.500000  0.744048  0.009650  0.609938  0.362945         8

avg / total   0.995835  0.743437  0.500610  0.850522  0.609938  0.381058      3200

-----------------------------------------------------------------------------------
Fit time :  0.07387924194335938
-----------------------------------------------------------------------------------

√ LogisticRegression(C=0.01, class_weight='balanced', random_state=4,
                   solver='liblinear')

[[2354  838]
 [   4    4]]
------------------------------------------------------
                   pre       rec       spe        f1       geo       iba       sup

          0   0.998304  0.737469  0.500000  0.848288  0.607235  0.377491      3192
          1   0.004751  0.500000  0.737469  0.009412  0.607235  0.359978         8

avg / total   0.995820  0.736875  0.500594  0.846191  0.607235  0.377447      3200

-----------------------------------------------------------------------------------
Fit time :  0.06872987747192383
-----------------------------------------------------------------------------------

/Users/rudan/miniforge3/envs/tf/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/rudan/miniforge3/envs/tf/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)